### PR TITLE
 jupysql v0.10.15 (amend update)

### PR DESCRIPTION
**Pull request by flaviomartins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by flaviomartins** [comment]
@edublancas ready for your review

**Comment by flaviomartins** [comment]
@conda-forge-admin please re-lint

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
@flaviomartins this usually takes about an hour to be live, please test it and let me know if everything works as expected

**Comment by flaviomartins** [comment]
> @flaviomartins this usually takes about an hour to be live, please test it and let me know if everything works as expected

@edublancas Seems to be working just fine.

**Comment by edublancas** [comment]
awesome, thanks!

**Pull request merged**
